@ stdcall BuildHimcList(ptr long ptr)
@ stdcall CtfImmTIMDestroyInputContext(ptr)
@ stdcall DestroyImeModeSaver(ptr)
@ stdcall DestroyInputContext(ptr ptr long)
@ stdcall FindOrLoadImeDpi(ptr)
@ stdcall ImmLocalAlloc(long long)
@ stdcall PtiCurrent()
@ stdcall Internal_CtfImeDestroyInputContext(ptr)
@ stdcall UnloadIME(ptr long)
