@ stdcall DestroyInputContext(ptr ptr long)
@ stdcall FindOrLoadImeDpi(ptr)
@ stdcall ImmLocalAlloc(long long)
@ stdcall BuildHimcList(ptr long ptr)
@ stdcall PtiCurrent()
@ stdcall CtfImmTIMDestroyInputContext(ptr)
